#pragma config(Sensor, S1,     touch,               sensorTouch)
#pragma config(Sensor, S2,     light,               sensorLightActive)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
TJoystick joystick;

void lineTracking()
{
	   getJoystickSettings(joystick);
     while(SensorValue[light] < 43 && (joystick.joy1_Buttons == 32))
	  	{
	      getJoystickSettings(joystick);
		  	motor[motorB] = 40;
		    motor[motorC] = 80;
		  	//bend left while over tape
	  	}

	    while(SensorValue[light] >= 43 && joystick.joy1_Buttons == 32)
	    {
	    	getJoystickSettings(joystick);
        motor[motorC] = 40;
		    motor[motorB] = 80;


			//bend right when off of tape stripe
	    }
}


void motorControlProportional()
{
  int nMotorPower;
  int nDirection;
  nMotorPower = joystick.joy1_y2;
  nDirection = joystick.joy1_x2;

  if(joystick.joy1_Buttons == 16) //turbo mode
  {
  motor[motorB] = joystick.joy1_y2 * (95.0/128) + joystick.joy1_x2 * (65.0/128);
  motor[motorC] = joystick.joy1_y2 * (95.0/128) - joystick.joy1_x2 * (65.0/128);
  }
  else
  {
  motor[motorB] = 0.50*(joystick.joy1_y2 * (95.0/128) + joystick.joy1_x2 * (65.0/128));
  motor[motorC] = 0.50*(joystick.joy1_y2 * (95.0/128) - joystick.joy1_x2 * (65.0/128));
  }
}

task main()
{
	while(true)
	{
		getJoystickSettings(joystick);
    if(joystick.joy1_Buttons != 32)  //while not in line tracking mode
    {
      getJoystickSettings(joystick);
      motorControlProportional();
    }
    else if(joystick.joy1_Buttons == 32)
    {
     getJoystickSettings(joystick);
     lineTracking();
    }

  }

}
